version: '3'

vars:
  PROTOBUF_VERSION: "32.1"
  # GNU grep support depending on OS
  GREP_CMD:
    sh: |
      case "$(uname)" in
        Darwin*) echo ggrep ;;
        Linux*) echo grep ;;
      esac

tasks:

  bash-add-go-path:
    desc: "Add Go binary folder to .bashrc if it does not already exists"
    internal: true
    platforms: ["linux/amd64"]
    cmds:
      - grep -qx 'export PATH="$PATH:$(go env GOPATH)/bin"' ~/.bashrc || echo 'export PATH="$PATH:$(go env GOPATH)/bin"' >> ~/.bashrc
      - source ~/.bashrc

  # Public task to install Go vulnerability checking tool
  install-go-vulnerability-check:
    desc: "Install Go vulnerability checking tool"
    cmds:
      - task: install-go-vulnerability-check-linux-amd64
      - task: install-go-vulnerability-check-darwin

  install-go-vulnerability-check-linux-amd64:
    desc: "Install Go vulnerability checking tool for Linux"
    internal: true
    deps: [bash-add-go-path]
    platforms: ["linux/amd64"]
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  install-go-vulnerability-check-darwin:
    desc: "Install Go vulnerability checking tool for Apple/macOS"
    internal: true
    platforms: ["darwin"]
    cmds:
      - brew install govulncheck

  ################# Build Go CLI ####################
  build:
    desc: "Build CLI"
    deps: [format, lint]
    dir: .
    cmds:
      - go build -o ./bin/go-client-cli main.go
    sources:
      - main.go
      - internal/**/*.go
      - ./*.go
      - go.mod
      - go.sum
    generates:
      - bin/go-client-cli

  build-docker:
    desc: "Build Docker image for the Go client app"
    vars:
      TAG: '{{.TAG | default "latest"}}'
    dotenv: ['.env']
    cmds:
      - docker buildx build -f ./docker/Dockerfile -t test_app_go:{{.TAG}} .

  delete-binaries:
    desc: "Delete binary artifacts"
    cmds:
      - rm bin/*

  ################# Tests ####################
  test-hash:
    deps: [build]
    desc: "Test hashing command with Default profile"
    cmds:
      - ./bin/go-client-cli hash "Hello" --profile=Default

  test-health:
    deps: [build]
    desc: "Test health check command"
    cmds:
      - ./bin/go-client-cli health

  test-benchmark:
    deps: [build]
    desc: "Test benchmark command"
    cmds:
      - ./bin/go-client-cli benchmark

  test-sign:
    deps: [build]
    desc: "Test certificate signing command with Default profile"
    cmds:
      - |
        TMP_DIR=tmp-tests
        TEST_CA_DIR=../crypto-broker-deployment/testing/certificates/test-ca
        TEST_CSR_DIR=../crypto-broker-deployment/testing/certificates/test-csr
        rm -rf $TMP_DIR
        mkdir -p $TMP_DIR
        SIGNED_CERTIFICATE=$(./bin/go-client-cli --profile=Default sign --csr=$TEST_CSR_DIR/csr-nist-secp256r1.csr --caCert=$TEST_CA_DIR/cert-test-CA-nist-secp384r1.pem --caKey=$TEST_CA_DIR/test-CA-nist-secp384r1.pem | {{.GREP_CMD}} -oP '\"signedCertificate\":\s?"\K[^"]+')
        printf "$SIGNED_CERTIFICATE" > $TMP_DIR/cert-response.pem
        openssl x509 -inform PEM -in $TMP_DIR/cert-response.pem -text

  ################# Continuous Improvement Tasks ####################
  check-dependencies:
    desc: "Set the dependencies"
    cmds:
      - go mod tidy && go mod verify

  format:
    desc: "Apply formatting rules to Go code"
    cmds:
      - go fmt ./...

  lint:
    desc: "Apply linting to Go code"
    cmds:
      - go vet ./...

  unit-test:
    desc: "Run unit-tests"
    cmds:
      - go test ./... -cover

  vulnerability-check:
    desc: "Run vulnerability check"
    deps: [install-go-vulnerability-check]
    cmds:
      - govulncheck ./...

  ci:
    desc: "Runs continuous integration checks on source code"
    cmds:
      - task: check-dependencies
      - task: format
      - task: lint
      - task: unit-test
      - task: vulnerability-check
