name: Go Continuous Improvement

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  go-pipeline:
    runs-on: ubuntu-latest
    container:
      image: golang
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Install Task
        uses: go-task/setup-task@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run benchmarks
        continue-on-error: true
        run: |
          git config --global --add safe.directory /__w/crypto-broker-cli-go/crypto-broker-cli-go
          git clone -b main --single-branch https://github.com/open-crypto-broker/crypto-broker-server.git
          git submodule update --init
          cd crypto-broker-server
          mkdir profiles
          cp example-profiles/Profile.yaml profiles/Profile.yaml
          CRYPTO_BROKER_PROFILES_DIR=$(pwd)/profiles OTEL_TRACES_SAMPLER=always_off go run cmd/server/server.go &
          cd ..
          task run-benchmarks

      - name: Run CI task from Taskfile
        run: task ci
